[phases.setup]
nixPkgs = ["nodejs_18", "python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install imapclient"
]

[start]
cmd = "node server.js"
