[phases.setup]
nixPkgs = ["nodejs_20", "python312", "python312Packages.pip", "python312Packages.setuptools"]

[phases.install]
cmds = [
  "npm install",
  "pip3 install imapclient beautifulsoup4 --break-system-packages"
]

[start]
cmd = "node server.js"
